# utils.py



# Map slugs to proper subject names
subject_slugs = {
    "engineering_mathematics": "Engineering Mathematics",
    "statistics_analytics": "Statistics & Analytics",
    "it_skills": "IT Skills",
    "feee": "FEEE",
    "pms": "PMS"
}
sample_mcqs = {
    "Engineering Mathematics": [
        {"question": "Derivative of x^3?", "options": ["3x^2","x^2","x^3","3x"], "correct": "1"},
        {"question": "Integral of x dx?", "options": ["x^2","x^2/2","2x","1/x"], "correct": "2"},
        {"question": "Limit of (1+1/n)^n as n→∞?", "options": ["0","1","e","∞"], "correct": "3"},
        {"question": "Derivative of sin(x)?", "options": ["cos(x)","-cos(x)","sin(x)","-sin(x)"], "correct": "1"},
        {"question": "Integral of cos(x) dx?", "options": ["sin(x)","-sin(x)","cos(x)","-cos(x)"], "correct": "1"},
        {"question": "Derivative of e^x?", "options": ["e^x","xe","x^2","1"], "correct": "1"},
        {"question": "Integral of 1/x dx?", "options": ["ln(x)","x","1/x^2","e^x"], "correct": "1"},
        {"question": "Limit of sin(x)/x as x→0?", "options": ["0","1","∞","-1"], "correct": "2"},
        {"question": "Derivative of ln(x)?", "options": ["1/x","x","ln(x)","-1/x"], "correct": "1"},
        {"question": "Integral of e^x dx?", "options": ["e^x","x e^x","ln(x)","1"], "correct": "1"},
        {"question": "Derivative of cos(x)?", "options": ["-sin(x)","sin(x)","cos(x)","-cos(x)"], "correct": "1"},
        {"question": "Limit of (x^2 -1)/(x-1) as x→1?", "options": ["0","2","1","∞"], "correct": "2"},
        {"question": "Integral of x^2 dx?", "options": ["x^3/3","x^2/2","x^3","2x^2"], "correct": "1"},
        {"question": "Derivative of tan(x)?", "options": ["sec^2(x)","tan(x)","cos^2(x)","1"], "correct": "1"},
        {"question": "Integral of 1/(1+x^2) dx?", "options": ["arctan(x)","ln(x)","1/x","x"], "correct": "1"},
        {"question": "Limit of (1 - cos(x))/x^2 as x→0?", "options": ["0","1/2","1","∞"], "correct": "2"},
        {"question": "Derivative of x sin(x)?", "options": ["sin(x)+x cos(x)","x cos(x)","sin(x)","x sin(x)"], "correct": "1"},
        {"question": "Integral of sin(x) dx?", "options": ["-cos(x)","cos(x)","sin(x)","-sin(x)"], "correct": "1"},
        {"question": "Limit of (e^x-1)/x as x→0?", "options": ["0","1","∞","-1"], "correct": "2"},
        {"question": "Derivative of x^n?", "options": ["n x^(n-1)","x^n","n x^n","x^(n-1)"], "correct": "1"},
        {"question": "Integral of 1/(x^2) dx?", "options": ["-1/x","1/x","x","-x"], "correct": "1"},
        {"question": "Derivative of arcsin(x)?", "options": ["1/sqrt(1-x^2)","sqrt(1-x^2)","x","1"], "correct": "1"},
        {"question": "Limit of ln(1+x)/x as x→0?", "options": ["0","1","∞","-1"], "correct": "2"},
        {"question": "Integral of cos(2x) dx?", "options": ["sin(2x)/2","2 sin(x)","cos(2x)/2","sin(x)"], "correct": "1"},
        {"question": "Derivative of sec(x)?", "options": ["sec(x)tan(x)","sec(x)","tan(x)","1"], "correct": "1"},
        {"question": "Integral of 1/(sqrt(1-x^2)) dx?", "options": ["arcsin(x)","arccos(x)","x","1"], "correct": "1"},
        {"question": "Limit of x*sin(1/x) as x→0?", "options": ["0","1","∞","-1"], "correct": "1"},
        {"question": "Derivative of ln(sin(x))?", "options": ["cot(x)","tan(x)","1/sin(x)","-cot(x)"], "correct": "1"},
        {"question": "Integral of x e^x dx?", "options": ["x e^x - e^x","e^x","x e^x","-e^x"], "correct": "1"},
        {"question": "Limit of (x^2+3x)/(x) as x→0?", "options": ["0","3","∞","1"], "correct": "1"},
    ],

    "Statistics & Analytics": [
        {"question": "Mean of 2,4,6?", "options": ["2","4","6","12"], "correct": "2"},
        {"question": "Probability of head in coin toss?", "options": ["0.25","0.5","0.75","1"], "correct": "2"},
        {"question": "Median of 1,3,5?", "options": ["1","3","5","9"], "correct": "2"},
        {"question": "Variance of 2,4,6?", "options": ["1","2","4","8"], "correct": "3"},
        {"question": "Standard deviation is?", "options": ["sqrt(variance)","variance^2","mean","median"], "correct": "1"},
        {"question": "Random variable takes?", "options": ["Single value","Multiple values","Unknown","None"], "correct": "2"},
        {"question": "Mode of 1,1,2,3?", "options": ["1","2","3","0"], "correct": "1"},
        {"question": "Probability of rolling 6 on die?", "options": ["1/6","1/5","1/4","1/3"], "correct": "1"},
        {"question": "Cumulative frequency shows?", "options": ["Sum frequency","Mean","Median","Mode"], "correct": "1"},
        {"question": "Event with certain outcome?", "options": ["Impossible","Sure","Random","Dependent"], "correct": "2"},
        {"question": "Random experiment example?", "options": ["Toss coin","2+2","Derivative","Integral"], "correct": "1"},
        {"question": "Range of data?", "options": ["Max - Min","Mean","Variance","Median"], "correct": "1"},
        {"question": "Probability range?", "options": ["0 to 1","-1 to 1","0 to 100","-∞ to ∞"], "correct": "1"},
        {"question": "Outlier definition?", "options": ["Extreme value","Average","Median","Mode"], "correct": "1"},
        {"question": "Skewness measures?", "options": ["Symmetry","Variance","Mean","Median"], "correct": "1"},
        {"question": "Kurtosis measures?", "options": ["Peakedness","Variance","Mean","Median"], "correct": "1"},
        {"question": "Z-score represents?", "options": ["Standard deviation","Mean","Median","Mode"], "correct": "1"},
        {"question": "Correlation ranges?", "options": ["-1 to 1","0 to 1","0 to 100","-∞ to ∞"], "correct": "1"},
        {"question": "Regression predicts?", "options": ["Dependent","Independent","Both","None"], "correct": "1"},
        {"question": "Sampling method example?", "options": ["Random","Mean","Median","Mode"], "correct": "1"},
        {"question": "Poisson distribution used for?", "options": ["Rare events","Mean","Median","Mode"], "correct": "1"},
        {"question": "Binomial distribution?", "options": ["Two outcomes","Multiple outcomes","Continuous","None"], "correct": "1"},
        {"question": "Central Limit Theorem states?", "options": ["Sample mean → Normal","Population mean","Variance","Mode"], "correct": "1"},
        {"question": "Probability of complement?", "options": ["1-P(E)","P(E)","0","∞"], "correct": "1"},
        {"question": "Conditional probability?", "options": ["P(A|B)","P(B|A)","P(A)+P(B)","0"], "correct": "1"},
        {"question": "Covariance measures?", "options": ["Relationship","Variance","Mean","Median"], "correct": "1"},
        {"question": "Probability density function?", "options": ["Continuous probability","Discrete","Mean","Variance"], "correct": "1"},
        {"question": "Expected value?", "options": ["Mean","Variance","Median","Mode"], "correct": "1"},
        {"question": "What is a probability distribution?", "options": ["List of outcomes and probabilities","List of numbers","Graph only","None"], "correct": "1"},
        {"question": "A data set with values 2,2,3 has mode?", "options": ["2","3","Cannot determine","None"], "correct": "1"},
    ],

    "IT Skills": [
        {"question": "HTML stands for?", "options": ["HTML","CSS","JS","HTTP"], "correct": "1"},
        {"question": "CSS is used for?", "options": ["Style","Logic","Database","Networking"], "correct": "1"},
        {"question": "JS is used for?", "options": ["Interactivity","Database","Styling","Networking"], "correct": "1"},
        {"question": "Python is?", "options": ["Programming","Styling","Markup","Database"], "correct": "1"},
        {"question": "SQL is?", "options": ["Database","Styling","Programming","Networking"], "correct": "1"},
        {"question": "Bootstrap is?", "options": ["CSS Framework","Python library","DB","JS library"], "correct": "1"},
        {"question": "Responsive design?", "options": ["Adapt screen","Logic","DB","Networking"], "correct": "1"},
        {"question": "Hyperlink tag in HTML?", "options": ["<a>","<p>","<div>","<link>"], "correct": "1"},
        {"question": "Table row tag?", "options": ["<tr>","<td>","<th>","<table>"], "correct": "1"},
        {"question": "Form tag?", "options": ["<form>","<input>","<textarea>","<label>"], "correct": "1"},
        {"question": "JS function?", "options": ["function myFunc(){}","<function>","func()","def"], "correct": "1"},
        {"question": "DOM stands for?", "options": ["Document Object Model","Data Object Model","Design Object Model","None"], "correct": "1"},
        {"question": "HTTP stands for?", "options": ["HyperText Transfer Protocol","HyperText Test Protocol","HighText Transfer Protocol","None"], "correct": "1"},
        {"question": "URL stands for?", "options": ["Uniform Resource Locator","Uniform Resource Link","Universal Resource Locator","None"], "correct": "1"},
        {"question": "IP stands for?", "options": ["Internet Protocol","Internal Protocol","Internet Process","None"], "correct": "1"},
        {"question": "CPU stands for?", "options": ["Central Processing Unit","Central Performance Unit","Computer Processing Unit","None"], "correct": "1"},
        {"question": "RAM stands for?", "options": ["Random Access Memory","Read Access Memory","Read Array Memory","None"], "correct": "1"},
        {"question": "ROM stands for?", "options": ["Read Only Memory","Random Only Memory","Read Object Memory","None"], "correct": "1"},
        {"question": "DNS stands for?", "options": ["Domain Name System","Domain Number System","Data Name System","None"], "correct": "1"},
        {"question": "HTTP status 404?", "options": ["Page not found","Success","Server error","Redirect"], "correct": "1"},
        {"question": "Function of CSS?", "options": ["Styling","Logic","Database","Networking"], "correct": "1"},
        {"question": "JS variable?", "options": ["let","var","const","All"], "correct": "4"},
        {"question": "JS loop?", "options": ["for","while","do-while","All"], "correct": "4"},
        {"question": "JS array?", "options": ["[]","{}","()","<>"], "correct": "1"},
        {"question": "HTML image tag?", "options": ["<img>","<image>","<src>","<picture>"], "correct": "1"},
        {"question": "Input tag in form?", "options": ["<input>","<textarea>","<label>","<form>"], "correct": "1"},
        {"question": "CSS selector for id?", "options": ["#id"," .class","element","*"], "correct": "1"},
        {"question": "CSS selector for class?", "options": [".class","#id","element","*"], "correct": "1"},
        {"question": "JS event click?", "options": ["onclick","onhover","onchange","oninput"], "correct": "1"},
        {"question": "What does CSS stand for?", "options": ["Cascading Style Sheets","Computer Style Syntax","Colorful Style Scripts","None"], "correct": "1"},
    ],

    "PMS": [
        {"question": "Project Life Cycle phases?", "options": ["Initiation, Planning, Execution, Closure","Planning only","Execution only","All"], "correct": "1"},
        {"question": "Critical Path Method is for?", "options": ["Scheduling","Budgeting","Hiring","Coding"], "correct": "1"},
        {"question": "Gantt Chart shows?", "options": ["Timeline","Budget","Employees","All"], "correct": "1"},
        {"question": "Risk Management is?", "options": ["Identify & Control Risks","Budget","Coding","Design"], "correct": "1"},
        {"question": "Scope Management is?", "options": ["Project Scope","Time","Budget","Quality"], "correct": "1"},
        {"question": "Stakeholder definition?", "options": ["Person interested in project","Coding","Budget","Design"], "correct": "1"},
        {"question": "Resource Management?", "options": ["Allocate & Control Resources","Budget","Coding","Time"], "correct": "1"},
        {"question": "Work Breakdown Structure?", "options": ["Divide tasks","Budget","Coding","Design"], "correct": "1"},
        {"question": "Milestone in project?", "options": ["Key achievement","Task","Resource","Budget"], "correct": "1"},
        {"question": "Project Closure means?", "options": ["Finish project & document","Coding","Design","Time"], "correct": "1"},
        {"question": "Earned Value Analysis?", "options": ["Measure performance","Budget","Design","Coding"], "correct": "1"},
        {"question": "PERT chart is?", "options": ["Network diagram","Budget","Resource chart","Time chart"], "correct": "1"},
        {"question": "Project Baseline?", "options": ["Original plan","Budget","Coding","Design"], "correct": "1"},
        {"question": "Project Charter?", "options": ["Authorize project","Budget","Design","Coding"], "correct": "1"},
        {"question": "Project Budget?", "options": ["Allocate funds","Design","Coding","Time"], "correct": "1"},
        {"question": "Project Schedule?", "options": ["Timeline","Budget","Coding","Design"], "correct": "1"},
        {"question": "Change Management?", "options": ["Control changes","Budget","Coding","Design"], "correct": "1"},
        {"question": "Quality Management?", "options": ["Ensure quality","Budget","Coding","Design"], "correct": "1"},
        {"question": "Communication Plan?", "options": ["Share info","Budget","Coding","Design"], "correct": "1"},
        {"question": "Project Monitoring?", "options": ["Track progress","Budget","Coding","Design"], "correct": "1"},
        {"question": "Project Evaluation?", "options": ["Assess outcomes","Budget","Coding","Design"], "correct": "1"},
        {"question": "Project Reporting?", "options": ["Report status","Budget","Coding","Design"], "correct": "1"},
        {"question": "Project Documentation?", "options": ["Record details","Budget","Coding","Design"], "correct": "1"},
        {"question": "Project Resource Planning?", "options": ["Plan resources","Budget","Coding","Design"], "correct": "1"},
        {"question": "Project Kick-off?", "options": ["Start project","Budget","Coding","Design"], "correct": "1"},
        {"question": "Project Stakeholder Analysis?", "options": ["Identify stakeholders","Budget","Coding","Design"], "correct": "1"},
        {"question": "Project Risk Assessment?", "options": ["Identify risks","Budget","Coding","Design"], "correct": "1"},
        {"question": "Project Scope Statement?", "options": ["Document project scope","Budget","Coding","Design"], "correct": "1"},
        {"question": "Project Time Management?", "options": ["Manage schedule","Budget","Coding","Design"], "correct": "1"},
        {"question": "A stakeholder is?", "options": ["Interested party","Project manager","Developer","Designer"], "correct": "1"},
    ],

    "FEEE": [
    {"question": "Ohm's law states?", "options": ["V=IR","P=VI","E=MC2","F=ma"], "correct": "1"},
    {"question": "Unit of Electric Current?", "options": ["Volt","Ampere","Ohm","Watt"], "correct": "2"},
    {"question": "Unit of Voltage?", "options": ["Volt","Ampere","Ohm","Watt"], "correct": "1"},
    {"question": "Unit of Resistance?", "options": ["Ohm","Volt","Ampere","Watt"], "correct": "1"},
    {"question": "Power formula?", "options": ["P=VI","V=IR","E=MC2","F=ma"], "correct": "1"},
    {"question": "Series resistance formula?", "options": ["R_total = R1+R2+...","R_total = R1*R2","R_total = 1/R1 + 1/R2","R_total = V/I"], "correct": "1"},
    {"question": "Parallel resistance formula?", "options": ["1/R_total = 1/R1 + 1/R2","R_total = R1+R2","R_total = R1*R2","R_total = V/I"], "correct": "1"},
    {"question": "Electric power unit?", "options": ["Watt","Volt","Ampere","Ohm"], "correct": "1"},
    {"question": "Kirchhoff's Current Law states?", "options": ["Sum of currents at junction = 0","Voltage in loop=0","P=VI","F=ma"], "correct": "1"},
    {"question": "Kirchhoff's Voltage Law states?", "options": ["Sum of voltages in loop = 0","Current in junction=0","P=VI","V=IR"], "correct": "1"},
    {"question": "Capacitance unit?", "options": ["Farad","Henry","Watt","Volt"], "correct": "1"},
    {"question": "Inductance unit?", "options": ["Henry","Farad","Watt","Volt"], "correct": "1"},
    {"question": "Resistor color code: Red means?", "options": ["2","0","1","5"], "correct": "1"},
    {"question": "Resistor color code: Black means?", "options": ["0","1","2","5"], "correct": "1"},
    {"question": "Energy stored in capacitor formula?", "options": ["E=1/2 C V^2","E=CV","E=VI","E=IR"], "correct": "1"},
    {"question": "Reactance of capacitor formula?", "options": ["Xc = 1/(2πfC)","Xc = 2πfC","Xc = V/I","Xc = IR"], "correct": "1"},
    {"question": "Reactance of inductor formula?", "options": ["Xl = 2πfL","Xl = 1/(2πfL)","Xl = V/I","Xl = IR"], "correct": "1"},
    {"question": "Unit of frequency?", "options": ["Hertz","Volt","Ampere","Ohm"], "correct": "1"},
    {"question": "AC stands for?", "options": ["Alternating Current","Active Current","Ampere Current","Atomic Charge"], "correct": "1"},
    {"question": "DC stands for?", "options": ["Direct Current","Digital Current","Differential Current","Dependent Current"], "correct": "1"},
    {"question": "Power factor =?", "options": ["cosθ","sinθ","tanθ","1"], "correct": "1"},
    {"question": "Phase difference in pure resistor?", "options": ["0°","90°","180°","45°"], "correct": "1"},
    {"question": "Phase difference in pure inductor?", "options": ["90°","0°","180°","45°"], "correct": "1"},
    {"question": "Phase difference in pure capacitor?", "options": ["-90°","0°","90°","180°"], "correct": "1"},
    {"question": "Impedance unit?", "options": ["Ohm","Volt","Ampere","Watt"], "correct": "1"},
    {"question": "RMS value of AC?", "options": ["V_peak / √2","V_peak","V_peak*2","V_avg"], "correct": "1"},
    {"question": "Current leads voltage in?", "options": ["Capacitor","Inductor","Resistor","Both"], "correct": "1"},
    {"question": "Voltage leads current in?", "options": ["Inductor","Capacitor","Resistor","Both"], "correct": "1"},
    {"question": "Transformer works on?", "options": ["AC","DC","Both","None"], "correct": "1"},
    {"question": "Step-up transformer increases?", "options": ["Voltage","Current","Resistance","Power"], "correct": "1"},
]
}# end of sample_mcqs dictionary
